export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  SAVE_FILTER:"SAVE_FILTER",
  ONCLICK:"ON_CLICK",
  SAVE_CONTENTS:"SAVE_CONTENTS",
  SAVE_CONTENTS_TITLE:"SAVE_CONTENTS_TITLE",
  SAVE_CONTENTS_DES:"SAVE_CONTENTS_DES"

};
